(function () {
  'use strict';
  const svg = (label, contents) => `<svg viewBox="0 0 560 280" role="img" aria-label="${label}" xmlns="http://www.w3.org/2000/svg"><style>text{font-family:Arial,sans-serif;fill:#193345;font-size:16px}.small{font-size:13px}.line{stroke:#72939f;stroke-width:2}</style>${contents}</svg>`;
  const table = (caption, headers, rows) => `<table><caption>${caption}</caption><thead><tr>${headers.map(h => `<th scope="col">${h}</th>`).join('')}</tr></thead><tbody>${rows.map(r => `<tr>${r.map((c, i) => i ? `<td>${c}</td>` : `<th scope="row">${c}</th>`).join('')}</tr>`).join('')}</tbody></table>`;
  window.EARTH_SPACE_VISUALS = {
    motions: { title: 'Lab notebook / motion log', html: table('Three ball-and-lamp models', ['Model', 'Spins on its axis', 'Travels around lamp'], [['A', 'Yes', 'No'], ['B', 'No', 'Yes'], ['C', 'Yes', 'Yes']]), caption: 'The lamp remains fixed in all three models.' },
    dayglobe: { title: 'Observe / a sunlit globe', html: svg('Sunlight enters from the left. P is on the illuminated left half of a globe and Q is on its dark right half.', `<defs><clipPath id="globeClip"><circle cx="340" cy="140" r="94"/></clipPath></defs><circle cx="58" cy="140" r="35" fill="#efb849"/><text x="40" y="203">Sun</text>${[83,120,160,197].map(y => `<path d="M110 ${y} H228 l-10 -5 m10 5 l-10 5" fill="none" stroke="#d19b2a" stroke-width="3"/>`).join('')}<circle cx="340" cy="140" r="94" fill="#67b6c4"/><rect x="340" y="40" width="110" height="200" fill="#203749" clip-path="url(#globeClip)"/><ellipse cx="340" cy="140" rx="94" ry="31" fill="none" stroke="#ffffff" opacity=".4"/><circle cx="297" cy="140" r="7" fill="#16384b"/><text x="289" y="126" font-weight="bold">P</text><circle cx="390" cy="140" r="7" fill="#ffffff"/><text x="382" y="126" style="fill:white" font-weight="bold">Q</text><text x="276" y="263" class="small">Simplified equatorial view</text>`), caption: 'Schematic: size and distance are not to scale. P and Q are fixed places on the globe.' },
    shadows: { title: 'Field notes / a sunny day', html: table('One fixed upright stick on level ground', ['Time', 'Shadow length'], [['08:00', '120 cm'], ['10:00', '55 cm'], ['12:00', '20 cm'], ['16:00', '100 cm']]), caption: 'Measurements from one example day and place. These are not universal shadow lengths.' },
    shadowmodels: { title: 'Compare / light angle', html: svg('Setup A has a low lamp and a long shadow; setup B has a high lamp and a short shadow. The upright sticks are the same height.', `<text x="25" y="32" font-weight="bold">A / low lamp</text><text x="300" y="32" font-weight="bold">B / high lamp</text><path d="M20 221 H265 M295 221 H540" class="line"/><path d="M115 220 V152 M390 220 V152" stroke="#193345" stroke-width="9"/><circle cx="30" cy="95" r="18" fill="#efb849"/><circle cx="335" cy="52" r="18" fill="#efb849"/><path d="M30 95 L217 220 M335 52 L427 220" stroke="#d4a443" stroke-width="2" stroke-dasharray="6 4"/><path d="M115 221 H217 M390 221 H427" stroke="#58717a" stroke-width="9"/><text x="131" y="255" class="small">shadow</text><text x="380" y="255" class="small">shadow</text>`), caption: 'Same stick height and level surface. Diagrams are schematic; lamp angles differ.' },
    planetstrip: { title: 'Map / outward from the Sun', html: `<div class="planet-strip"><span class="strip-sun">SUN</span>${['Mercury', 'Venus', 'Earth', 'Mars', 'Jupiter', 'Saturn', 'Uranus', 'Neptune'].map((p, i) => `<span class="planet-item"><b class="planet-dot p${i}"></b><strong>${i + 1}</strong><small>${p}</small></span>`).join('')}</div>`, caption: 'Order only. Sizes, spacing and alignment are not to scale or current positions.' },
    objectcards: { title: 'Evidence / identify the objects', html: table('Observations of four objects', ['Object', 'Evidence'], [['A', 'Rocky body orbiting the Sun'], ['B', 'Ice and dust; releases gas near the Sun'], ['C', 'Natural body orbiting a planet'], ['D', 'Surviving space material found on the ground']]), caption: 'Use the observations to classify each object.' },
    worlds: { title: 'Compare / three imaginary worlds', html: table('Simplified surface observations', ['World', 'Water at surface', 'Temperature'], [['A', 'Ice only', 'Very cold'], ['B', 'Liquid water', 'Moderate'], ['C', 'No liquid water', 'Very hot']]), caption: 'These are imaginary worlds. Suitable conditions alone do not prove that life exists.' }
  };
})();
