(function(){
  'use strict';
  const D=window.CRYSTAL_LESSON, C=window.CRYSTAL_CHALLENGE, KEY='science-explorers-vanishing-crystal-v1';
  const $=id=>document.getElementById(id), esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const clean=()=>({version:1,index:0,challenge:C.fresh(),answers:{},notes:{},ink:{},revealed:{},review:{},visited:[],reflection:{},lab:{material:'salt',stirred:false,particle:0,filter:'salt',filtered:false,evap:0}});
  let state=clean(), saveOK=true;
  try{const raw=JSON.parse(localStorage.getItem(KEY)||'null');if(raw?.version===1){state.challenge=C.restore(raw.challenge);for(const key of ['answers','notes','ink','revealed','review','reflection','lab'])if(raw[key]&&typeof raw[key]==='object'&&!Array.isArray(raw[key]))state[key]={...state[key],...raw[key]};state.index=Math.max(0,Math.min(D.slides.length-1,Number.isInteger(raw.index)?raw.index:0));state.visited=Array.isArray(raw.visited)?raw.visited.filter(id=>D.slides.some(s=>s.id===id)):[];}}catch(_){saveOK=false;}
  let teacherMode=false, penMode='pen', activeStroke=null, boardSlide=null, confirmAction=null, player=null, clipIndex=0, videoGeneration=0, playerTimeout=null, stopTimer=null, apiPromise=null;
  const current=()=>D.slides[state.index];
  function save(){try{localStorage.setItem(KEY,JSON.stringify(state));saveOK=true;}catch(_){saveOK=false;}$('saveStatus').textContent=saveOK?'Saved on this device':'Saving unavailable — export your lesson record';}
  function download(name,content,type){const url=URL.createObjectURL(new Blob([content],{type})),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
  function confirmDo(text,action){$('confirmText').textContent=text;confirmAction=action;$('confirmDialog').showModal();}
  function closeVideo(){videoGeneration++;clearTimeout(playerTimeout);clearInterval(stopTimer);playerTimeout=null;stopTimer=null;if(player){try{player.destroy();}catch(_){}}player=null;}
  function recordVisit(){if(!state.visited.includes(current().id))state.visited.push(current().id);save();}
  function go(index){closeVideo();state.index=Math.max(0,Math.min(D.slides.length-1,index));recordVisit();render();$('lesson').focus({preventScroll:true});window.scrollTo({top:0,behavior:'instant'});}
  function svg(body,label){return `<svg viewBox="0 0 440 300" role="img" aria-label="${esc(label)}" xmlns="http://www.w3.org/2000/svg">${body}</svg>`;}
  function beaker(x,y,w=145,h=175,water=true){return `<path d="M${x},${y+9} V${y+h-14} Q${x},${y+h} ${x+14},${y+h} H${x+w-14} Q${x+w},${y+h} ${x+w},${y+h-14} V${y+9}" fill="${water?'#c2dde0':'#f7f8ec'}" fill-opacity=".68" stroke="#597f79" stroke-width="3"/><path d="M${x-5},${y+8} H${x+w+5}" stroke="#597f79" stroke-width="3"/>${water?`<path d="M${x+3},${y+44} Q${x+w/2},${y+52} ${x+w-3},${y+44}" fill="none" stroke="#79a8ac" stroke-width="2"/>`:''}${[70,95,120].map(v=>`<path d="M${x+w-22},${y+v} h13" stroke="#648d88" stroke-width="2"/>`).join('')}`;}
  function label(x,y,t,size=15){return `<text x="${x}" y="${y}" text-anchor="middle" fill="#173d3b" font-family="Segoe UI,Arial,sans-serif" font-size="${size}">${t}</text>`;}
  function grains(x,y,n=12,colour='#bd693c'){return Array.from({length:n},(_,i)=>`<rect x="${x+(i%6)*11}" y="${y-Math.floor(i/6)*11}" width="7" height="7" rx="1.5" transform="rotate(${i%2?12:-8} ${x+(i%6)*11} ${y-Math.floor(i/6)*11})" fill="${colour}"/>`).join('');}
  function art(kind){
    if(kind==='mystery')return svg(`${beaker(42,65)}${grains(83,215)}${beaker(252,65)}${label(113,275,'Before stirring')}${label(324,275,'After stirring')}<path d="M207 145h22m-8-8 8 8-8 8" stroke="#5f8272" stroke-width="2" fill="none"/>${label(325,185,'?',55)}`,'Salt crystals before stirring; a clear liquid after stirring. Where did the salt go?');
    if(kind==='two-clear')return svg(`${beaker(40,58)}${beaker(255,58)}${label(112,267,'Glass A')}${label(327,267,'Glass B')}${label(220,28,'Both look clear',14)}`,'Two clear liquids that cannot be distinguished by appearance.');
    if(kind==='melt')return svg(`<rect x="57" y="81" width="94" height="94" rx="12" fill="#d4e8e7" stroke="#699a9b" stroke-width="2" transform="rotate(-10 103 127)"/><ellipse cx="105" cy="216" rx="65" ry="17" fill="#aacfd5"/>${label(105,269,'Ice → liquid water')}${beaker(255,52)}${label(325,269,'Salt + water')}`,'Ice changes into liquid water; salt mixes into water.');
    if(kind==='recovery')return svg(`<circle cx="347" cy="61" r="27" fill="#dec976"/><path d="M60 193Q85 252 220 252T380 193Z" fill="#eff2de" stroke="#5d8479" stroke-width="3"/><ellipse cx="220" cy="193" rx="160" ry="31" fill="#bddbe0" stroke="#5d8479" stroke-width="2"/>${grains(169,202,12)}<path d="M175 150q-13-18 0-34t0-34M218 155q-13-18 0-34t0-34" stroke="#7daba7" stroke-width="3" fill="none" stroke-dasharray="5 6"/>${label(220,286,'A shallow dish. A little time.')}`,'A shallow dish of salt solution and a warm place.');
    if(kind==='test')return svg(`${beaker(35,50)}${beaker(255,50)}<path d="M110 35l35 148" stroke="#7e927e" stroke-width="6" stroke-linecap="round"/>${grains(70,194)}${grains(292,194)}${label(109,255,'Stirred')}${label(328,255,'Not stirred')}${label(220,285,'What must stay the same?',13)}`,'Two cups for comparing stirring while keeping other conditions the same.');
    if(kind==='zoom')return svg(`${beaker(60,58)}<circle cx="290" cy="141" r="83" fill="#f7f8eb" stroke="#6c927b" stroke-width="2" stroke-dasharray="5 7"/>${label(290,153,'?',65)}<path d="M345 204l38 45" stroke="#6c927b" stroke-width="12" stroke-linecap="round"/>${label(125,270,'What would a model show?',14)}`,'A clear beaker beside an empty magnified view for your particle model.');
    return svg(`${beaker(145,46,160,184)}<path d="M84 84h31m-8-7 8 7-8 7" stroke="#6c8b74" stroke-width="2" fill="none"/>${grains(46,69,6,kind==='sugar'?'#e3ba58':'#bd693c')}${label(220,269,kind==='sugar'?'Sugar + water':'Salt + water')}`,'A small amount of solid dissolves in water to make a solution.');
  }
  function scene(kind,caption){return `<div class="scene"><div class="scene-label"><span>FIELD OBSERVATION</span><span>01 / CRYSTAL LAB</span></div>${art(kind)}<p class="scene-caption">${caption||'A simplified teaching diagram. Look for evidence, then explain.'}</p></div>`;}
  function header(s){return `<h1>${s.title}</h1><p class="lead">${s.lead}</p>`;}
  function written(s){return `<label class="field-label" for="response">Your explanation</label><textarea id="response" rows="4" placeholder="${esc(s.frame||'I noticed… because…')}">${esc(state.notes[s.id]||'')}</textarea><div class="actions"><button id="drawHere">Draw your thinking ↗</button><span class="small">Drawing + words both count.</span></div>`;}
  function render(){
    window.CRYSTAL_MOTION?.stop();
    closeVideo();
    const s=current();$('phaseLabel').textContent=(s.optional?'OPTIONAL CHALLENGE · ': '')+D.phases[s.phase].toUpperCase();$('pageNumber').textContent=String(state.index+1).padStart(2,'0')+' / '+D.slides.length;$('progressBar').style.width=((state.index+1)/D.slides.length*100)+'%';
    $('phaseNav').innerHTML=D.phases.map((p,i)=>`<button class="phase-button" data-phase="${i}" ${s.phase===i?'aria-current="step"':''}><span>${String(i+1).padStart(2,'0')}</span>${p}</button>`).join('');
    $('phaseNav').querySelectorAll('button').forEach(b=>b.onclick=()=>go(D.slides.findIndex(x=>x.phase===Number(b.dataset.phase))));
    $('previous').disabled=state.index===0;$('next').textContent=state.index===D.slides.length-1?'Mission map ↗':'Next discovery →';
    let body='';
    if(s.type==='mcq')body=`<div class="split">${scene(s.scene)}<section class="question-card"><span class="pill">${s.diagnostic?'PREDICT · NO SCORE':s.exit?'INDEPENDENT CHECK':'YOUR TURN'}</span><h2>${s.question}</h2><div class="options">${s.options.map((v,i)=>`<button class="option" data-option="${i}" aria-pressed="${state.answers[s.id]?.choice===i}"><span class="letter">${String.fromCharCode(65+i)}</span><span>${v}</span></button>`).join('')}</div><div class="actions"><button id="check" class="primary">${s.diagnostic?'Save my prediction':'Check my reasoning'}</button><button id="hint" class="quiet">A little hint</button></div><div id="feedback" class="feedback" role="status" hidden></div></section></div>`;
    else if(s.type==='written')body=`<div class="split">${scene(s.scene)}<section class="question-card"><span class="pill">${s.id==='boss'?'BOSS CHALLENGE':'PREDICT & DRAW'}</span><p class="prompt">${s.prompt}</p>${written(s)}<p class="hint">Explain your idea to your teacher. Your explanation is reviewed together, not automatically scored.</p></section></div>`;
    else if(s.type==='reveal'){const n=state.revealed[s.id]||0;body=`<div class="split">${scene(s.scene)}<section class="question-card"><div class="reveal-list">${s.reveals.map((r,i)=>`<div class="reveal-row">${i<n?`<h3>${r[0]}</h3><p>${r[1]}</p>`:`<div class="reveal-cover">Discovery ${i+1} · ready to reveal</div>`}</div>`).join('')}</div><div class="actions"><button id="reveal" class="primary" ${n>=s.reveals.length?'disabled':''}>Reveal next idea</button><button id="hideReveal" class="quiet" ${n===0?'disabled':''}>One step back</button></div><p class="hint">Say it first, then reveal. Space also reveals the next idea.</p></section></div>`;}
    else if(s.type==='compare')body=compareContent();
    else if(s.type==='particles')body=particleContent();
    else if(s.type==='filter')body=filterContent();
    else if(s.type==='evaporation')body=evapContent();
    else if(s.type==='video')body=videoContent();
    else if(s.type==='summary')body=summaryContent();
    $('stage').innerHTML=header(s)+body;
    if(s.type==='mcq'){
      document.querySelectorAll('[data-option]').forEach(b=>b.onclick=()=>{const a=state.answers[s.id]||(state.answers[s.id]={});a.choice=Number(b.dataset.option);a.checked=false;save();document.querySelectorAll('[data-option]').forEach(el=>el.setAttribute('aria-pressed',el===b?'true':'false'));$('feedback').hidden=true;});
      $('check').onclick=()=>{const a=state.answers[s.id];if(!a||D.grade(s,a.choice)===null){feedback('Choose an idea first.','try');return;}if(!a.checked){const correct=D.grade(s,a.choice);if(!s.diagnostic)window.CRYSTAL_FEEDBACK?.respond(correct,a.firstCorrect===undefined);if(a.firstCorrect===undefined)a.firstCorrect=correct;a.attempts=(a.attempts||0)+1;a.correct=correct;a.checked=true;save();}showAnswer(s,a);};
      $('hint').onclick=()=>feedback(s.hint);if(state.answers[s.id]?.checked)showAnswer(s,state.answers[s.id]);
    }
    if($('response'))$('response').oninput=e=>{state.notes[s.id]=e.target.value;save();};
    if($('drawHere'))$('drawHere').onclick=openBoard;
    if($('reveal')){$('reveal').onclick=()=>{state.revealed[s.id]=Math.min(s.reveals.length,(state.revealed[s.id]||0)+1);save();render();};$('hideReveal').onclick=()=>{state.revealed[s.id]=Math.max(0,(state.revealed[s.id]||0)-1);save();render();};}
    bindLab(s);if(s.type==='video')bindVideo();if(s.type==='summary')bindSummary();window.CRYSTAL_MOTION?.mount(s,state);
  }
  function feedback(text,kind=''){$('feedback').hidden=false;$('feedback').className='feedback '+kind;$('feedback').textContent=text;}
  function showAnswer(s,a){feedback(s.diagnostic?'Prediction saved. Keep your idea in mind as we collect evidence.':a.correct?'Yes — '+s.explain:'Take another look. '+s.hint,a.correct||s.diagnostic?'':'try');}
  function compareContent(){const salt=state.lab.material==='salt',stir=state.lab.stirred;return `<div class="split"><div class="scene"><div class="scene-label"><span>OBSERVATION LAB</span><span>NOT TO SCALE</span></div>${svg(`${beaker(139,37,165,195)}${stir&&salt?'':grains(185,213,18,salt?'#bd693c':'#887654')}${label(220,270,salt?'A little salt + water':'Sand + water')}`,stir&&salt?'After stirring: clear salt solution, no visible crystals.':'Solid grains visible in water.')}<p class="scene-caption">We use enough water for this small amount of salt to dissolve completely.</p></div><section class="question-card"><h2>Choose, predict, observe.</h2><div class="segmented"><button data-material="salt" aria-pressed="${salt}">Salt</button><button data-material="sand" aria-pressed="${!salt}">Sand</button></div><p class="prompt">Will the grains still be visible after stirring?</p><button id="stir" class="primary">${stir?'Stir again':'Stir & observe'}</button><div class="feedback">${!stir?'Make a prediction before you stir.':salt?'No crystals are visible. The liquid looks clear: the salt has dissolved.':'The sand does not dissolve. Grains may swirl while stirring, then settle when left to stand.'}</div><p class="hint">Compare both materials. Does mixing always produce a solution?</p></section></div>`;}
  function particleArt(step){const water=Array.from({length:36},(_,i)=>`<circle cx="${74+(i%9)*36}" cy="${85+Math.floor(i/9)*42}" r="7" fill="#4d8da4" opacity=".7"/>`).join('');const positions=[[118,105],[220,117],[317,92],[152,158],[280,152],[111,217],[220,217],[323,206]];const salt=positions.map((p,i)=>{const start=[172+(i%4)*23,225-Math.floor(i/4)*23];const ratio=step/2;const x=start[0]+(p[0]-start[0])*ratio,y=start[1]+(p[1]-start[1])*ratio;return `<rect x="${x}" y="${y}" width="12" height="12" rx="2" fill="#be642f"/>`;}).join('');return svg(`<rect x="44" y="47" width="351" height="219" rx="17" fill="#eaf2e7" stroke="#87a89d" stroke-width="2"/>${water}${salt}`,'Particle model: water circles and eight salt symbols, '+['clustered before dissolving','separating from the crystal','spread through the water'][step]+'. All eight salt symbols remain.');}
  function particleContent(){const step=Math.max(0,Math.min(2,state.lab.particle));return `<div class="split"><div class="scene"><div class="scene-label"><span>PARTICLE MODEL</span><span>ZOOMED-IN IDEA</span></div>${particleArt(step)}<div class="key"><span><i></i>Water</span><span><i class="salt"></i>Salt</span></div><p class="scene-caption">Symbols show an idea, not real colours or sizes. Real particles keep moving.</p></div><section class="question-card"><h2>${['Before dissolving','During dissolving','After dissolving'][step]}</h2><p class="prompt">${['The salt particles start together in a crystal.','Particles from the salt separate and mix among the water particles.','The salt particles are distributed throughout the water. The salt has not vanished.'][step]}</p><div class="step-dots">${[0,1,2].map(i=>`<span class="${i<=step?'on':''}"></span>`).join('')}</div><div class="segmented">${['Before','During','After'].map((t,i)=>`<button data-particle="${i}" aria-pressed="${i===step}">${t}</button>`).join('')}</div><div class="evidence-note"><strong>8 → 8</strong><span>Salt symbols before and after.<br>Nothing is deleted from this model.</span></div><button id="drawHere">Draw or revise your model ↗</button></section></div>`;}
  function filterArt(salt,ran){return svg(`<path d="M83 34h274L240 151v44h-40v-44Z" fill="#f4efdd" stroke="#729482" stroke-width="3"/><path d="M95 45l125 102L345 45" fill="none" stroke="#c9b889" stroke-width="4"/>${ran&&!salt?grains(191,122,12,'#887654'):''}<path d="M165 190v77h110v-77" fill="${ran?'#c2dde0':'none'}" stroke="#648f88" stroke-width="3"/>${ran?`<path d="M220 160v61" stroke="#71a5ae" stroke-dasharray="6 7" stroke-width="3"/>`:''}${label(220,25,'Ordinary filter paper',14)}${label(220,292,ran?(salt?'Saltwater passes through':'Water passes through'):'Predict before you filter',14)}`,ran?(salt?'Dissolved salt and water pass through filter paper together.':'Sand remains on filter paper while water passes through.'):'Funnel with ordinary filter paper above an empty beaker.');}
  function filterContent(){const salt=state.lab.filter==='salt',ran=state.lab.filtered;return `<div class="split"><div class="scene">${filterArt(salt,ran)}<p class="scene-caption">The diagram shows ordinary filter paper. Dissolved particles are too small for it to trap.</p></div><section class="question-card"><h2>What stays on the paper?</h2><div class="segmented"><button data-filter="salt" aria-pressed="${salt}">Salt solution</button><button data-filter="sand" aria-pressed="${!salt}">Sand + water</button></div><p class="prompt">Predict what you will collect below the filter.</p><button id="runFilter" class="primary">Run filter</button><div class="feedback">${!ran?'Make your prediction, then test it.':salt?'The liquid collected is still saltwater. Filtering has not recovered the dissolved salt.':'Sand stays on the filter paper. Water passes through. The sand did not dissolve.'}</div><p class="hint">If filtering cannot recover the salt, what else could you try?</p></section></div>`;}
  function evapContent(){const n=Math.max(0,Math.min(2,state.lab.evap));const diagram=svg(`<path d="M50 171q35 81 170 81t170-81" fill="${n===2?'#f6efda':'#bddbe0'}" stroke="#63877a" stroke-width="3"/><ellipse cx="220" cy="171" rx="170" ry="32" fill="${n===2?'#f6efda':'#bddbe0'}" stroke="#63877a" stroke-width="2"/>${n===2?grains(151,190,24):''}${n>0?'<path d="M150 126q-17-24 0-45t0-31M220 129q-17-24 0-45t0-31M290 126q-17-24 0-45t0-31" fill="none" stroke="#609aa7" stroke-width="3" stroke-dasharray="6 7"/>':''}${label(220,286,['Salt solution','Water leaves as vapour','Solid salt remains'][n])}`,'Evaporation sequence: '+['a dish containing salt solution','water evaporating from the solution','after the water has evaporated, salt remains'][n]);return `<div class="split"><div class="scene"><div class="scene-label"><span>RECOVERY MODEL</span><span>TIME COMPRESSED</span></div>${diagram}<p class="scene-caption">This takes time. Water can evaporate at room temperature; it does not need to boil.</p></div><section class="question-card"><span class="pill">${n+1} / 3</span><h2>${['Begin with a solution.','Let the water evaporate.','Look for the salt.'][n]}</h2><p class="prompt">${['The salt is dissolved in the water. We cannot pick it out with ordinary filter paper.','Liquid water changes into water vapour, a gas, and spreads into the air. The salt does not leave with it.','When the water has evaporated, solid salt remains. Dissolving can be reversed.'][n]}</p><div class="actions"><button id="evapNext" class="primary" ${n===2?'disabled':''}>Reveal next step</button><button id="evapBack" class="quiet" ${n===0?'disabled':''}>One step back</button></div><div class="callout">${n===2?'Next investigation: could we collect the water as well?':'Track both substances: where is the water, and where is the salt?'}</div></section></div>`;}
  function bindLab(s){
    document.querySelectorAll('[data-material]').forEach(b=>b.onclick=()=>{state.lab.material=b.dataset.material;state.lab.stirred=false;save();render();});if($('stir'))$('stir').onclick=()=>{if(state.lab.stirred){window.CRYSTAL_MOTION?.replay();return;}state.lab.stirred=true;save();render();};
    document.querySelectorAll('[data-particle]').forEach(b=>b.onclick=()=>{state.lab.particle=Number(b.dataset.particle);save();render();});
    document.querySelectorAll('[data-filter]').forEach(b=>b.onclick=()=>{state.lab.filter=b.dataset.filter;state.lab.filtered=false;save();render();});if($('runFilter'))$('runFilter').onclick=()=>{if(state.lab.filtered){window.CRYSTAL_MOTION?.replay();return;}state.lab.filtered=true;save();render();};
    if($('evapNext')){$('evapNext').onclick=()=>{state.lab.evap=Math.min(2,state.lab.evap+1);save();render();};$('evapBack').onclick=()=>{state.lab.evap=Math.max(0,state.lab.evap-1);save();render();};}
  }
  const stamp=n=>String(Math.floor(n/60)).padStart(2,'0')+':'+String(n%60).padStart(2,'0');
  function videoContent(){const c=D.clips[clipIndex];return `<div class="split"><section><div id="videoBox" class="video-box"><div class="video-placeholder"><div class="play-icon" aria-hidden="true">▷</div><p>Canadian Museum of Nature<br>How Water Dissolves Salt</p><button id="playClip">Play ${stamp(c.start)}–${stamp(c.end)}</button><p>Loads YouTube only when you press play.</p></div></div><div class="video-controls"><button id="replayClip">Replay this clip</button><button id="pauseClip">Pause</button><a id="youtubeLink" class="button-link" href="${D.watchURL(c)}" target="_blank" rel="noopener">Open YouTube at ${stamp(c.start)} ↗</a></div><p id="videoStatus" class="video-status" role="status">Embedded clips stop at the marked end. On YouTube, pause manually at ${stamp(c.end)}.</p><p class="small">Animation, not microscope footage. Focus on the moving particles; you do not need to learn the charge symbols today.</p></section><section class="question-card">${D.clips.map((v,i)=>`<button class="video-card" data-clip="${i}" aria-pressed="${i===clipIndex}"><span class="eyebrow">${stamp(v.start)} — ${stamp(v.end)}</span><strong>${v.title}</strong><small>${v.focus}</small></button>`).join('')}<label class="field-label" for="response">What did you notice?</label><textarea id="response" rows="3" placeholder="The salt particles…">${esc(state.notes.video||'')}</textarea><div class="actions"><button id="useModel">Use the built-in model →</button></div><p class="hint">No video? You can complete the whole investigation with the built-in model.</p></section></div>`;}
  function loadAPI(){if(window.YT?.Player)return Promise.resolve();if(apiPromise)return apiPromise;apiPromise=new Promise((resolve,reject)=>{const previous=window.onYouTubeIframeAPIReady;window.onYouTubeIframeAPIReady=()=>{if(typeof previous==='function')previous();resolve();};const script=document.createElement('script');script.src='https://www.youtube.com/iframe_api';script.onerror=()=>{apiPromise=null;script.remove();reject(new Error('YouTube could not load.'));};document.head.appendChild(script);});return apiPromise;}
  function videoStatus(text){if($('videoStatus'))$('videoStatus').textContent=text;}
  async function playClip(){
    closeVideo();const generation=videoGeneration,c=D.clips[clipIndex];
    if(location.protocol==='file:'){videoStatus('For embedded playback, open the hosted preview or use the YouTube link. Local files cannot reliably identify their origin to YouTube.');return;}
    const iframe=document.createElement('iframe');iframe.id='ytPlayer-'+generation;iframe.title=c.title+' — Canadian Museum of Nature';iframe.src=D.embedURL(c,location.origin);iframe.allow='autoplay; encrypted-media; picture-in-picture; fullscreen';iframe.allowFullscreen=true;iframe.referrerPolicy='strict-origin-when-cross-origin';$('videoBox').classList.add('has-player');$('videoBox').replaceChildren(iframe);videoStatus('Loading the selected clip. If asked, press play inside the video.');
    playerTimeout=setTimeout(()=>{if(generation===videoGeneration)videoStatus('The player is taking longer than expected. Try the YouTube link, or continue with the built-in model.');},14000);
    try{
      await loadAPI();if(generation!==videoGeneration||!$(iframe.id))return;
      let ended=false;
      const finish=target=>{ended=true;clearInterval(stopTimer);target.pauseVideo();videoStatus('Clip finished at '+stamp(c.end)+'. '+c.focus);};
      player=new YT.Player(iframe.id,{events:{
        onReady:e=>{if(generation!==videoGeneration)return;clearTimeout(playerTimeout);videoStatus('Ready: '+stamp(c.start)+'–'+stamp(c.end)+'. Press play inside the video if needed.');e.target.loadVideoById({videoId:c.videoId,startSeconds:c.start,endSeconds:c.end});},
        onStateChange:e=>{
          if(generation!==videoGeneration)return;
          if(e.data===1){
            ended=false;clearTimeout(playerTimeout);videoStatus('Playing '+stamp(c.start)+'–'+stamp(c.end)+' · stops for discussion.');clearInterval(stopTimer);
            stopTimer=setInterval(()=>{if(generation===videoGeneration&&e.target.getCurrentTime()>=c.end-.15)finish(e.target);},100);
          }else if(e.data===0){finish(e.target);}
          else if(e.data===2){clearInterval(stopTimer);videoStatus(ended?'Clip finished at '+stamp(c.end)+'. '+c.focus:'Paused. '+c.focus);}
        },
        onError:e=>{if(generation!==videoGeneration)return;clearTimeout(playerTimeout);clearInterval(stopTimer);videoStatus('YouTube cannot play this embedded clip (code '+e.data+'). Open it on YouTube, or use the built-in model.');},
        onAutoplayBlocked:()=>videoStatus('Press play inside the video to begin the selected clip.')
      }});
    }catch(_){if(generation===videoGeneration)videoStatus('The embedded player could not initialise. Use the YouTube link or the built-in model.');}
  }
  function bindVideo(){document.querySelectorAll('[data-clip]').forEach(b=>b.onclick=()=>{closeVideo();clipIndex=Number(b.dataset.clip);render();});$('playClip').onclick=playClip;$('replayClip').onclick=playClip;$('pauseClip').onclick=()=>{if(player?.pauseVideo)player.pauseVideo();else{closeVideo();render();videoStatus('Video stopped. Your observation is saved.');}};$('useModel').onclick=()=>go(D.slides.findIndex(s=>s.id==='particles'));}
  function summaryContent(){const exits=D.slides.filter(s=>s.exit),attempted=exits.filter(s=>state.answers[s.id]?.firstCorrect!==undefined).length,first=exits.filter(s=>state.answers[s.id]?.firstCorrect).length,now=exits.filter(s=>state.answers[s.id]?.correct).length;return `<div id="challengeHost"></div><details class="lesson-reflection"><summary>Lesson reflection &amp; exit results</summary><div class="summary-grid"><div class="summary-tile"><strong>${first} / 3</strong><span>Exit questions correct<br>on the first attempt.</span></div><div class="summary-tile"><strong>${now} / 3</strong><span>Exit questions correct<br>after any corrections.</span></div><div class="summary-tile"><strong>${attempted} / 3</strong><span>Exit questions attempted.<br>Exploring is not a test score.</span></div></div><div class="reflection"><section><label class="field-label" for="usedToThink">I used to think…</label><textarea id="usedToThink" rows="3">${esc(state.reflection.before||'')}</textarea></section><section><label class="field-label" for="nowThink">Now I think… because…</label><textarea id="nowThink" rows="3">${esc(state.reflection.after||'')}</textarea></section></div><div class="callout"><strong>One question to take away.</strong> We recovered the salt. How could we collect the water too?</div><div class="actions"><button id="reviewExit">Revisit exit challenges</button></div></details><div class="actions"><button id="saveReport">Save my lesson record</button></div><p class="hint">Your teacher reviews drawings and explanations separately. Lesson checks allow corrections; challenge answers preserve your first submission.</p>`;}
  function bindSummary(){C.mount($('challengeHost'),state.challenge,{save,confirm:confirmDo,draw:openBoard});$('usedToThink').oninput=e=>{state.reflection.before=e.target.value;save();};$('nowThink').oninput=e=>{state.reflection.after=e.target.value;save();};$('reviewExit').onclick=()=>go(D.slides.findIndex(s=>s.exit));$('saveReport').onclick=exportReport;}
  function openMap(){$('mapList').innerHTML=D.slides.map((s,i)=>`<button class="map-row" data-page="${i}"><strong>${String(i+1).padStart(2,'0')} · ${s.title.replace(/<\/?em>/g,'')}</strong><span>${state.visited.includes(s.id)?'Visited':'Explore'}${s.optional?' · Optional':''}</span></button>`).join('');$('mapList').querySelectorAll('button').forEach(b=>b.onclick=()=>{$('mapDialog').close();go(Number(b.dataset.page));});$('mapDialog').showModal();}
  function openBoard(){window.CRYSTAL_MOTION?.pause();if(player?.pauseVideo)player.pauseVideo();const q=current().type==='summary'?C.question(state.challenge):null;boardSlide=q?'challenge-'+q.id:current().id;$('boardPrompt').textContent=q?q.question:current().prompt||current().question||current().lead;$('boardText').value=state.notes[boardSlide]||'';$('boardDialog').showModal();drawInk();}
  const canvas=$('ink'),ctx=canvas.getContext('2d');
  function strokes(){return Array.isArray(state.ink[boardSlide])?state.ink[boardSlide]:[];}
  function drawStroke(stroke){ctx.save();ctx.globalCompositeOperation=stroke.mode==='eraser'?'destination-out':'source-over';ctx.strokeStyle=stroke.colour;ctx.fillStyle=stroke.colour;ctx.lineWidth=stroke.width;ctx.lineCap='round';ctx.lineJoin='round';if(stroke.points.length===1){ctx.beginPath();ctx.arc(stroke.points[0][0],stroke.points[0][1],stroke.width/2,0,Math.PI*2);ctx.fill();}else{ctx.beginPath();stroke.points.forEach((p,i)=>i?ctx.lineTo(p[0],p[1]):ctx.moveTo(p[0],p[1]));ctx.stroke();}ctx.restore();}
  function drawInk(){ctx.clearRect(0,0,canvas.width,canvas.height);strokes().forEach(drawStroke);if(activeStroke)drawStroke(activeStroke);}
  function point(e){const r=canvas.getBoundingClientRect();return [(e.clientX-r.left)*canvas.width/r.width,(e.clientY-r.top)*canvas.height/r.height];}
  canvas.onpointerdown=e=>{if(e.button!==0||activeStroke)return;e.preventDefault();canvas.setPointerCapture(e.pointerId);activeStroke={pointer:e.pointerId,mode:penMode,colour:$('inkColor').value,width:penMode==='eraser'?28:Number($('inkWidth').value),points:[point(e)]};drawInk();};
  canvas.onpointermove=e=>{if(!activeStroke||activeStroke.pointer!==e.pointerId)return;e.preventDefault();activeStroke.points.push(point(e));drawInk();};
  function finishStroke(e){if(!activeStroke||(e&&activeStroke.pointer!==e.pointerId))return;const {pointer,...stroke}=activeStroke;state.ink[boardSlide]=[...strokes(),stroke];activeStroke=null;save();drawInk();}
  canvas.onpointerup=finishStroke;canvas.onpointercancel=finishStroke;canvas.onlostpointercapture=finishStroke;
  $('boardDialog').addEventListener('close',()=>{finishStroke();render();});
  $('boardText').oninput=e=>{state.notes[boardSlide]=e.target.value;save();};
  $('pen').onclick=()=>{penMode='pen';$('pen').setAttribute('aria-pressed','true');$('eraser').setAttribute('aria-pressed','false');};$('eraser').onclick=()=>{penMode='eraser';$('pen').setAttribute('aria-pressed','false');$('eraser').setAttribute('aria-pressed','true');};
  $('undoInk').onclick=()=>{state.ink[boardSlide]=strokes().slice(0,-1);save();drawInk();};$('clearInk').onclick=()=>confirmDo('Clear the drawing on this screen? Your written explanation will stay.',()=>{state.ink[boardSlide]=[];save();drawInk();});
  $('exportDrawing').onclick=()=>{const out=document.createElement('canvas');out.width=canvas.width;out.height=canvas.height;const c=out.getContext('2d');c.fillStyle='#fffef9';c.fillRect(0,0,out.width,out.height);c.drawImage(canvas,0,0);const a=document.createElement('a');a.download='crystal-'+boardSlide+'.png';a.href=out.toDataURL('image/png');a.click();};
  function teacher(){const s=current(),q=s.type==='summary'?C.question(state.challenge):null;$('teacherContent').innerHTML=`<span class="pill">Cambridge Primary Science 0097 · Stage 5 bridge</span><h3>${s.title.replace(/<\/?em>/g,'')}</h3><p>${s.teacher}</p>${q?`<div class="callout"><strong>Challenge answer: ${String.fromCharCode(65+q.answer)}. ${esc(q.options[q.answer])}</strong><br>${esc(q.explain)}</div>`:''}${s.type==='mcq'?`<div class="callout"><strong>Answer: ${String.fromCharCode(65+s.answer)}.</strong> ${s.explain}</div>`:''}${s.rubric?`<section class="teacher-section"><h3>Review the explanation together</h3><div class="rubric">${s.rubric.map((r,i)=>`<label><input type="checkbox" data-rubric="${i}" ${state.review[s.id]?.includes(i)?'checked':''}>${r}</label>`).join('')}</div><p class="small">An oral explanation or a labelled drawing may also meet a criterion. Tick only after reviewing.</p><details><summary>Example answer, not the only accepted wording</summary><p>${s.sample}</p></details></section>`:''}<section class="teacher-section"><h3>Flexible 60-minute teaching route</h3><p>按學生掌握程度調節：核心探索約 25–35 分鐘 → 最後一頁挑戰約 20–30 分鐘 → 反思 5 分鐘。題目需要口頭解釋，50 題是備用題庫，不必一堂全做。老師可在開始前選 10／20／30／40／50 題；每 10 題包含 4 題應用、4 題實驗推理、2 題延伸。Stretch 包含飽和度、數據計算、蒸餾、擴散與動態平衡，不視為 Stage 5 必修。</p><p>每題選一個最佳答案，先說理由再核對。首次提交後鎖定答案，解釋立即顯示。可跳題、返回，或提早結束；未答題不算錯。最後可展開答案回顧，或繼續未答題。最後一頁的書寫板會按題目保存。</p><p>先讓學生操作和表達，再揭示。Ctrl + Alt + T 開啟／關閉教師視圖。Space 在詞彙頁逐步揭示；左右方向鍵換頁（輸入或播放器操作時不攔截）。</p></section>`;$('teacherContent').querySelectorAll('[data-rubric]').forEach(b=>b.onchange=()=>{const values=new Set(state.review[s.id]||[]),n=Number(b.dataset.rubric);b.checked?values.add(n):values.delete(n);state.review[s.id]=[...values];save();});$('teacherDialog').showModal();teacherMode=true;}
  function exportReport(){const report={lesson:'The Vanishing Crystal',exportedAt:new Date().toISOString(),storage:'local-only',...state};download('vanishing-crystal-lesson-record.json',JSON.stringify(report,null,2),'application/json');}
  $('openMap').onclick=openMap;$('openBoard').onclick=openBoard;$('previous').onclick=()=>go(state.index-1);$('next').onclick=()=>state.index===D.slides.length-1?openMap():go(state.index+1);$('openSources').onclick=()=>$('sourcesDialog').showModal();
  $('mapSources').onclick=()=>{$('mapDialog').close();$('sourcesDialog').showModal();};
  $('fullScreen').onclick=async()=>{try{if(document.fullscreenElement)await document.exitFullscreen();else await document.documentElement.requestFullscreen();}catch(_){$('saveStatus').textContent='Use your browser’s full-screen command.';}};
  document.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>b.closest('dialog').close());$('teacherDialog').addEventListener('close',()=>{teacherMode=false;});$('exportReport').onclick=exportReport;
  $('resetLesson').onclick=()=>confirmDo('Reset all answers, drawings and notes for this investigation on this device? Export your lesson record first if you want to keep it.',()=>{state=clean();window.CRYSTAL_FEEDBACK?.reset();$('teacherDialog').close();go(0);});
  $('cancelConfirm').onclick=()=>{$('confirmDialog').close();confirmAction=null;};$('acceptConfirm').onclick=()=>{const fn=confirmAction;confirmAction=null;$('confirmDialog').close();if(fn)fn();};
  document.addEventListener('keydown',e=>{if(e.ctrlKey&&e.altKey&&e.key.toLowerCase()==='t'){e.preventDefault();if(teacherMode)$('teacherDialog').close();else if(!document.querySelector('dialog[open]'))teacher();return;}if(document.querySelector('dialog[open]')||/INPUT|TEXTAREA|SELECT|BUTTON|A|IFRAME/.test(e.target.tagName)||e.target.isContentEditable)return;if(current().type==='summary'&&C.question(state.challenge)&&(e.key==='ArrowRight'||e.key==='ArrowLeft')){e.preventDefault();const b=$(e.key==='ArrowRight'?'nextQuestion':'prevQuestion');if(b&&!b.disabled)b.click();return;}if(e.key==='ArrowRight'){e.preventDefault();go(state.index+1);}if(e.key==='ArrowLeft'){e.preventDefault();go(state.index-1);}if(e.code==='Space'&&$('reveal')&&!$('reveal').disabled){e.preventDefault();$('reveal').click();}});
  window.addEventListener('pagehide',()=>{finishStroke();save();closeVideo();});
  recordVisit();render();
})();
