(function(root){
  'use strict';
  // Original questions. Each source row gives the best answer first; rotate the
  // displayed options so answer positions are balanced and stable on reload.
  const rows=[
    ['apply','A sealed bottle contains 100 g of water and 5 g of salt. All the salt dissolves. What is the mass of the contents?',['105 g','100 g','95 g','It depends on whether the liquid looks clear.'],'Both substances remain in the bottle. Dissolving does not remove the 5 g of salt.'],
    ['apply','Sugar dissolves in water. Which description is correct?',['Sugar is the solute; water is the solvent.','Water is the solute; sugar is the solvent.','Both substances are solvents.','The solution is only the sugar.'],'The solute dissolves in the solvent. The whole mixture is the solution.'],
    ['apply','A clear liquid is labelled “salt solution”. What does its clear appearance tell you?',['No suspended grains can be seen; dissolved salt may still be present.','It contains only water.','It is safe to drink.','The salt has changed into water.'],'Clear does not mean pure or safe. Dissolved substances can be invisible to our eyes.'],
    ['apply','Sand and salt are mixed into enough water to dissolve all the salt. What does ordinary filter paper collect?',['Sand, while salt solution passes through.','Salt, while sand and water pass through.','Both sand and dissolved salt.','Pure water, while everything else passes through.'],'The paper traps sand grains. Dissolved salt travels through with the water.'],
    ['apply','A puddle becomes smaller on a cool day without boiling. What is happening?',['Liquid water is evaporating into the air.','Water is turning into solid air.','Evaporation is impossible without boiling.','The water particles are being destroyed.'],'Evaporation can happen at room temperature and below boiling temperature. Water enters the air as water vapour.'],
    ['apply','Ice becomes liquid water. How is this different from salt dissolving in water?',['Melting changes the state of one substance; dissolving mixes a solute with a solvent.','Both processes turn salt into water.','Melting needs a solvent but dissolving never does.','Dissolving always produces a gas.'],'Ice and liquid water are the same substance in different states. A salt solution contains water and dissolved salt.'],
    ['apply','Cup A has 2 g of salt in 100 g of water. Cup B has 4 g in 100 g of water. Both dissolve fully. Which is more concentrated?',['Cup B, because there is more salt for the same mass of water.','Cup A, because it contains less salt.','They are equally concentrated because both are clear.','Neither, because dissolved salt has no mass.'],'Concentration describes how much solute there is relative to the amount of solution or solvent being compared. Here the water amounts are equal.'],
    ['apply','You add more water to a salt solution without spilling anything. Which change occurs?',['The solution becomes more dilute; the mass of salt stays the same.','The mass of salt decreases.','The salt becomes sand.','The solution becomes more concentrated.'],'Adding solvent spreads the same amount of solute through more water. This is dilution.'],
    ['apply','Half the water evaporates from a salt solution, and all the salt remains dissolved. What happens?',['The solution becomes more concentrated.','The solution becomes more dilute.','Half the salt must also evaporate.','The remaining liquid must be pure water.'],'The same salt is now mixed with less water. The question specifies that no crystals have formed yet.'],
    ['apply','You leave a little salt solution in a dish until all the water evaporates. What would you expect to find?',['Solid salt in the dish.','Only water vapour trapped in the open dish.','No material, because dissolved salt has vanished.','Sand made from the salt.'],'Water leaves as vapour. Under these conditions the salt remains and can form crystals.'],
    ['apply','A diagram shows eight salt markers before dissolving. Which after-diagram best conserves the salt?',['Eight salt markers spread among water markers.','Four salt markers spread among water markers.','Eight extra water markers and no salt markers.','No markers because a clear solution is empty.'],'Dissolving changes how the material is distributed, not the amount of salt. Markers are a simplified model, not literal colours or sizes.'],
    ['apply','After stirring, sand settles at the bottom of a cup. Which conclusion is best supported?',['The sand did not dissolve in the water.','The sand dissolved and then became water.','Every substance is soluble if stirred once.','The water has turned into sand.'],'Settling grains remain a separate solid. Stirring can suspend grains temporarily without dissolving them.'],
    ['apply','A pupil says, “The sugar disappeared, so it no longer exists.” What is the strongest correction?',['It may be dissolved and still present even though crystals are no longer visible.','Anything invisible has no mass.','Sugar always evaporates when stirred.','A clear liquid cannot contain another substance.'],'Visibility alone is not evidence that a substance has stopped existing. Dissolved sugar is still part of the solution.'],
    ['apply','A teacher pours salt solution through ordinary filter paper. How should the collected liquid be labelled?',['Salt solution.','Pure water.','Dry salt.','Sand suspension.'],'Ordinary filter paper does not remove dissolved salt from water.'],
    ['apply','Which observation is evidence for a change of state, rather than dissolving?',['Pure ice becomes liquid water without another substance being added.','Sugar is stirred into tea.','Salt crystals mix into water.','A spoonful of salt forms a clear solution.'],'Melting changes solid water into liquid water. It does not require a second substance to act as a solvent.'],
    ['apply','All the salt has dissolved in a well-mixed cup. A small sample is taken from the top. What should it contain?',['Water and dissolved salt.','Only water, because salt always stays at the bottom.','Only dry salt.','No matter, because it is clear.'],'In a well-mixed solution, dissolved salt is distributed throughout the water, including the top.'],
    ['apply','Which method best recovers dry salt from salt solution?',['Allow the water to evaporate and keep the solid residue.','Use ordinary filter paper alone.','Stir until the salt becomes visible again.','Add more water and collect the water.'],'Removing the solvent by evaporation leaves the salt. Adding water makes the solution more dilute.'],
    ['apply','Which pair can look similar while having different compositions?',['Pure water and a clear salt solution.','A salt crystal and an empty beaker only.','Two samples must have the same composition if both are clear.','Only coloured liquids can have different compositions.'],'Appearance cannot reliably identify dissolved substances. Both samples may look clear even though one contains salt.'],
    ['apply','Water vapour touches a cool surface and forms liquid drops. What is this change called?',['Condensation.','Dissolving.','Melting.','Filtration.'],'Condensation is a change from gas to liquid. It can help us collect water after evaporation.'],
    ['apply','Which statement about the particle animation is most sensible?',['It helps explain spreading, but its colours and particle sizes are not literal.','Salt particles are really orange squares.','Water particles stop moving once salt dissolves.','There are exactly eight salt particles in every cup.'],'A scientific model shows selected ideas. It is not an exact picture of the real system.'],

    ['investigate','To test whether stirring changes dissolving time, which pair is fairest?',['Same salt mass, water amount and temperature; stir one cup only.','Stir a hot cup with more water and compare it with a cold cup.','Use sugar in one cup and sand in the other.','Use different salt masses and stir both cups.'],'Change only the factor being tested. Otherwise a difference in time could have another cause.'],
    ['investigate','A pupil tests water temperature. What should they measure to find out which temperature dissolves a fixed amount of sugar fastest?',['Time until no sugar crystals remain visible, using the same observation rule each time.','The colour of the empty cup.','Only the starting mass of the cup.','The number of times they say “dissolve”.'],'The outcome is dissolving time. A consistent end point makes comparisons more meaningful.'],
    ['investigate','The same dissolving test gives 40 s, 42 s and 41 s. Why repeat it?',['To see how consistent the results are and reduce the influence of random variation.','To guarantee the expected answer.','To change every variable each time.','To prove that measurement errors are impossible.'],'Repeated measurements help reveal variation. They do not guarantee perfect measurements.'],
    ['investigate','A set of repeated results is 39 s, 40 s and 95 s. What is the best next action?',['Check notes and repeat the test before deciding how to treat 95 s.','Delete 95 s immediately because it is inconvenient.','Change 95 s to 40 s without explanation.','Conclude that all the measurements are useless.'],'An unusual result is a reason to investigate, not to silently edit the evidence.'],
    ['investigate','Sugar dissolves in 70 s in cool water and 25 s in warm water. The warm cup was also stirred more. What can you conclude?',['The test cannot separate the effects of temperature and stirring.','Temperature alone caused the entire difference.','Stirring never matters.','Warm water always dissolves every solid.'],'Two factors changed together. Repeat with the same stirring to investigate temperature fairly.'],
    ['investigate','Two identical dishes contain equal amounts of the same solution. One is covered and one is open. Why might the open dish lose water faster?',['Water vapour can leave the open dish more easily.','The cover changes salt into water.','Covered water has no particles.','Only open water can ever change into a gas.'],'A cover limits vapour escaping to the room and can allow water to condense back. It does not stop particle motion.'],
    ['investigate','A wide dish and a narrow cup contain the same water volume. Temperature and airflow are the same. Which prediction is most reasonable?',['The wide dish may lose water faster because more surface is exposed.','The narrow cup must lose water faster because it is taller.','Surface area cannot affect evaporation.','Neither can lose water below boiling point.'],'Evaporation occurs at the liquid surface. Exposing more surface can increase the rate.'],
    ['investigate','A teacher wants to compare two clear liquids without tasting them. Both leave different amounts of dry residue after equal samples evaporate. What does this show?',['The samples contained different amounts of non-volatile dissolved material.','The sample with less residue was definitely safe to drink.','Both samples were definitely pure water.','The residue identifies every dissolved substance by name.'],'Residue gives evidence about material left behind. It does not by itself identify every substance or establish drinking safety.'],
    ['investigate','A closed container and its contents weigh 180 g before dissolving. Nothing enters or leaves. What result would best support conservation of mass?',['180 g after dissolving, within measurement uncertainty.','Less than 180 g because the crystals are invisible.','More than 180 g because stirring creates matter.','Zero because the solution is clear.'],'Compare the same whole closed system before and after. Small differences can come from the balance rather than a real loss of matter.'],
    ['investigate','An open dish of salt solution becomes lighter overnight. Does this disprove conservation of mass?',['No. Water can leave the measured dish as vapour.','Yes. All lost mass has been destroyed.','Yes. Dissolved salt has no mass.','No. Balances can never measure solutions.'],'The measured dish is an open system. Include the water that entered the surroundings when tracking all the matter.'],
    ['investigate','A pupil compares one large sugar cube with the same mass of crushed sugar. What must also be kept the same?',['Water amount, water temperature and stirring method.','Only the colour of the notebook.','The size of the sugar pieces, because that must not change.','Nothing: equal sugar mass makes every other condition irrelevant.'],'Particle size is the factor being tested. Keep the other factors that could affect dissolving time the same.'],
    ['investigate','With the same water and stirring, crushed sugar dissolves sooner than a cube of equal mass. Which explanation fits best?',['More sugar surface is in contact with water.','Crushing removes all the sugar mass.','Crushed sugar has become a different element.','The cube contains no particles.'],'Breaking a solid into smaller pieces exposes more total surface. It can change the rate without changing the substance.'],
    ['investigate','Two equal samples of the same salt solution are left in dishes. One loses more water but neither forms crystals. What is the best prediction?',['The sample that loses more water is more concentrated.','The sample that loses more water contains less salt because salt must evaporate too.','Both samples become pure water.','The more concentrated sample must be darker.'],'The salt remains while water leaves. Concentration can change without a visible colour change.'],
    ['investigate','A pupil adds salt until some remains after thorough stirring at a fixed temperature. Which next test helps check whether the water has reached its dissolving limit?',['Add a little more water and see whether the remaining salt can dissolve.','Conclude that stirring has destroyed the water.','Use appearance alone to say that all the salt is gone.','Weigh only the empty spoon.'],'Adding solvent can allow more salt to dissolve. The observation is consistent with the original water reaching its limit; enough mixing time matters too.'],
    ['investigate','Trial times are 30 s, 36 s and 33 s. What is their mean time?',['33 s','99 s','3 s','36 s'],'Add the times: 30 + 36 + 33 = 99. Divide by three trials: 33 s.'],
    ['investigate','In a fair test, a fixed mass of sugar takes 80 s to dissolve at 20°C and 40 s at 40°C. Which statement follows from these results?',['It took half as long at 40°C in this test.','It will take zero seconds at 60°C.','Every substance dissolves twice as fast at 40°C.','Twice as much sugar dissolved at 40°C.'],'The measured time halved. The test does not establish a universal rule or tell us the maximum amount that can dissolve.'],
    ['investigate','A mixture contains sand, salt and water. Which sequence best recovers the sand first and then the salt?',['Filter to collect sand, then evaporate water from the filtrate.','Evaporate all the water, then use dry filter paper to separate the mixed solids.','Filter twice to trap the dissolved salt.','Stir faster until the two solids disappear.'],'Filtration separates the insoluble sand. The filtrate is the liquid that passes through; evaporating its water leaves salt.'],
    ['investigate','A pupil says a solution is saturated because crystals are still visible after five seconds. What is the main problem?',['The crystals might simply need more time to dissolve.','Saturated solutions can never contain dissolved material.','Every solid always dissolves in five seconds.','Visible crystals prove that the liquid is pure water.'],'Saturated means no more of that solute can dissolve at the stated conditions. A brief wait alone does not establish that limit.'],
    ['investigate','A drop from a well-mixed solution leaves salt when it dries. Which conclusion is justified?',['That drop contained dissolved salt before drying.','Every clear liquid contains salt.','The whole cup was made only of salt.','Drying created salt from pure water.'],'The result supports a claim about this sample. It does not justify a claim about every clear liquid.'],
    ['investigate','A class measures dissolving time at 10°C, 20°C and 30°C. Which graph would best show how time changes with temperature?',['Temperature on the horizontal axis and dissolving time on the vertical axis.','Student names on both axes.','Dissolving time on both axes.','A graph with no labels or units.'],'Put the changed factor on the horizontal axis and the measured outcome on the vertical axis. Label temperature in °C and time in seconds.'],

    ['stretch','A fictional solid X dissolves up to 12 g in 100 g of water at 20°C. You add 17 g and allow enough mixing time. How much remains undissolved?',['5 g','12 g','17 g','29 g'],'The water can dissolve 12 g under these stated conditions. The extra 17 − 12 = 5 g remains solid. This is a model data problem.'],
    ['stretch','At one temperature, solid X dissolves up to 12 g per 100 g of water. What is the maximum in 50 g of water at the same temperature?',['6 g','12 g','24 g','50 g'],'Half as much water can dissolve half as much X under these stated conditions: 12 ÷ 2 = 6 g.'],
    ['stretch','Solid X dissolves up to 20 g per 100 g of water at 60°C, but only 8 g at 20°C. A solution of 20 g X in 100 g water cools to 20°C without losing water. Once it settles to the new limit, how much X crystallises?',['12 g','8 g','20 g','28 g'],'Only 8 g can remain dissolved at the lower temperature, so 20 − 8 = 12 g forms crystals. Use the supplied data; solids do not all behave identically.'],
    ['stretch','Distillation means evaporating water and then condensing its vapour in a separate container. Why can this collect water from salt solution?',['Water enters the vapour and is collected as liquid; the salt stays behind under these conditions.','Ordinary filter paper turns salt into water.','The salt must evaporate before any water does.','Condensation destroys the water particles.'],'Evaporation alone lets water escape. Distillation adds a way to cool and collect the vapour. This is a teacher-led concept, not a heating instruction.'],
    ['stretch','A solution contains 5 g of salt and 95 g of water. What percentage of its total mass is salt?',['5%','Approximately 5.3%','50%','95%'],'Total solution mass is 100 g. Salt mass percentage is 5 ÷ 100 × 100 = 5%. Dividing by water mass alone answers a different question.'],
    ['stretch','A solution contains 6 g of salt in 60 g of water. How much water must be added to halve its salt-to-water ratio?',['60 g','30 g','6 g','120 g'],'Keep the 6 g of salt and double the water from 60 g to 120 g. That requires adding 60 g. The question asks for the salt-to-water ratio.'],
    ['stretch','A drop of dye slowly spreads through still water. This spreading by random particle motion is called diffusion. Which explanation fits?',['Random motion can distribute dye from a concentrated region through the water.','Dye particles know where the empty spaces are and plan a route.','The dye must turn into water first.','Particles remain completely still unless a spoon pushes them.'],'Diffusion results from random motion, with a net spreading from higher to lower concentration. It does not require particles to have intentions.'],
    ['stretch','In a sealed jar, some water evaporates and some vapour condenses. Eventually the liquid level stays steady. Must the particles have stopped moving?',['No. Evaporation and condensation can continue at equal rates.','Yes. A steady level means every particle is frozen.','Yes. All the vapour has vanished permanently.','No. The jar must be leaking.'],'A steady overall amount can hide two continuing processes that balance. This idea is called dynamic equilibrium.'],
    ['stretch','A substance dissolves faster in warm water in one experiment. Does this alone prove that more of it can dissolve in warm water?',['No. Dissolving speed and the maximum amount that can dissolve are different measurements.','Yes. Faster always means a larger final amount.','Yes. The two measurements have the same units.','No. Warm water can never dissolve any substance.'],'Rate asks “how quickly?” Solubility asks “how much under these conditions?” A separate test is needed for the limit.'],
    ['stretch','A 150 g sealed apparatus contains saltwater and a separate collecting cup. Some water evaporates, then condenses into the cup. Nothing leaves the apparatus. What should the whole apparatus weigh afterwards?',['150 g, within measurement uncertainty.','Less than 150 g because the water changed state.','More than 150 g because condensation creates water.','The original mass minus the collected water mass.'],'Moving water between parts of a closed apparatus changes its location and state, not the total mass of the apparatus and its contents.']
  ];
  const bank=rows.map(([level,question,choices,explain],i)=>{const offset=i%4;return {id:'crystal-'+String(i+1).padStart(2,'0'),level,question,options:choices.map((_,j)=>choices[(j-offset+4)%4]),answer:offset,explain};});
  const sizes=[10,20,30,40,50], levels=['apply','investigate','stretch'];
  const names={apply:'Apply',investigate:'Investigate',stretch:'Stretch'};
  const fresh=()=>({size:10,ids:[],index:0,answers:{},ended:false});
  function sample(size,random=Math.random){if(!sizes.includes(size))throw new RangeError('Choose 10, 20, 30, 40 or 50 questions.');return levels.flatMap((level,k)=>{const pool=bank.filter(q=>q.level===level).map(q=>q.id);for(let i=pool.length-1;i>0;i--){const j=Math.floor(random()*(i+1));[pool[i],pool[j]]=[pool[j],pool[i]];}return pool.slice(0,size*[.4,.4,.2][k]);});}
  function restore(raw){const s=fresh();if(!raw||typeof raw!=='object')return s;if(sizes.includes(raw.size))s.size=raw.size;if(!Array.isArray(raw.ids)||raw.ids.length!==s.size||new Set(raw.ids).size!==s.size||raw.ids.some(id=>!bank.some(q=>q.id===id)))return s;s.ids=[...raw.ids];s.index=Math.max(0,Math.min(s.ids.length-1,Number.isInteger(raw.index)?raw.index:0));s.ended=raw.ended===true;for(const id of s.ids){const a=raw.answers?.[id];if(a&&Number.isInteger(a.choice)&&a.choice>=0&&a.choice<4)s.answers[id]={choice:a.choice,checked:a.checked===true};}return s;}
  function stats(s){const checked=s.ids.filter(id=>s.answers[id]?.checked);return {attempted:checked.length,correct:checked.filter(id=>bank.find(q=>q.id===id).answer===s.answers[id].choice).length,total:s.ids.length};}
  function question(s){return s.ids.length&&!s.ended?bank.find(q=>q.id===s.ids[s.index]):null;}
  function submit(s){const q=question(s),a=q&&s.answers[q.id];if(!a||a.checked||!Number.isInteger(a.choice)||a.choice<0||a.choice>3)return false;a.checked=true;return true;}
  function mount(host,s,{save,confirm,draw}){
    const esc=v=>String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
    const button=(id,label,extra='')=>`<button id="${id}" ${extra}>${label}</button>`;
    function repaint(focus=false){
      const q=question(s),r=stats(s);
      let body='';
      if(!s.ids.length)body=`<p class="challenge-intro">Choose your round, then explain your reasoning aloud. One best answer per question.</p><fieldset class="challenge-picker"><legend>Teacher · How many questions?</legend><div class="segmented">${sizes.map(n=>button('round-'+n,String(n),`data-size="${n}" aria-pressed="${s.size===n}" aria-label="${n} questions"`)).join('')}</div></fieldset><p class="hint">${s.size*.4} Apply · ${s.size*.4} Investigate · ${s.size*.2} Stretch<br>Every round builds towards harder ideas. Allow extra time to discuss your answers; you can end early.</p>${button('startRound','Start '+s.size+' questions →','class="primary"')}`;
      else if(s.ended)body=`<h3 tabindex="-1" id="roundHeading">Round complete</h3><div class="summary-grid"><div class="summary-tile"><strong>${r.correct} / ${r.attempted}</strong><span>Correct on first submission.</span></div><div class="summary-tile"><strong>${r.attempted} / ${r.total}</strong><span>Questions answered.</span></div><div class="summary-tile"><strong>${r.total-r.attempted}</strong><span>Unanswered — not marked wrong.</span></div></div><p class="hint">${r.attempted?'Use the explanations below to discuss ideas worth revisiting.':'No answers submitted in this round.'}</p><details class="challenge-review"><summary>Review submitted answers (${r.attempted})</summary>${s.ids.filter(id=>s.answers[id]?.checked).map(id=>{const item=bank.find(x=>x.id===id),a=s.answers[id];return `<article><span class="pill">${names[item.level]} · ${a.choice===item.answer?'Correct':'Revisit'}</span><h4>${esc(item.question)}</h4><p>Your answer: ${esc(item.options[a.choice])}</p><p><strong>Best answer: ${esc(item.options[item.answer])}</strong></p><p>${esc(item.explain)}</p></article>`;}).join('')}</details><div class="actions">${button('newRound','Choose another round')}${r.attempted<r.total?button('resumeRound','Continue unanswered questions','class="primary"'):''}</div><p class="hint">Save the lesson record below before replacing a round you want to keep.</p>`;
      else {const a=s.answers[q.id],checked=a?.checked,correct=a?.choice===q.answer;body=`<div class="challenge-meta"><span class="pill">${names[q.level]}${q.level==='stretch'?' · Beyond the lesson':''}</span><span>${s.index+1} / ${r.total} · ${r.attempted} answered</span></div><h3 id="roundHeading" tabindex="-1">${esc(q.question)}</h3><p class="small">Choose one best answer. Explain why before checking.</p><div class="options">${q.options.map((o,i)=>`<button class="option" data-answer="${i}" aria-pressed="${a?.choice===i}" ${checked?'disabled':''}><span class="letter">${String.fromCharCode(65+i)}</span><span>${esc(o)}</span></button>`).join('')}</div><div class="feedback ${checked&&!correct?'try':''}" id="roundFeedback" role="status" ${checked?'':'hidden'}>${checked?`<strong>${correct?'Correct.':'Let’s revisit this.'} Best answer: ${String.fromCharCode(65+q.answer)}.</strong> ${esc(q.explain)}`:''}</div><div class="actions">${button('checkRound',checked?'Answer recorded':'Check answer',`class="primary" ${checked?'disabled':''}`)}${button('drawRound','Explain on the writing board ↗')}</div><div class="challenge-navigation">${button('prevQuestion','← Previous',s.index===0?'disabled':'')}${button('nextQuestion',s.index===r.total-1?'Finish round →':checked?'Next question →':'Skip for now →')}${button('endRound','End round','class="quiet"')}</div><p class="hint">Answers lock when checked so your first attempt is preserved. You can skip and return to any unanswered question.</p>`;}
      host.innerHTML=`<section class="challenge-panel" aria-labelledby="challengeTitle"><div class="challenge-heading"><span class="eyebrow">EXTENDED LEARNING · 50-QUESTION BANK</span><h2 id="challengeTitle">Ready for <em>another challenge?</em></h2></div>${body}</section>`;
      const find=id=>host.querySelector('#'+id),on=(id,fn)=>{if(find(id))find(id).onclick=fn;};
      host.querySelectorAll('[data-size]').forEach(b=>b.onclick=()=>{s.size=Number(b.dataset.size);save();repaint();find('round-'+s.size).focus();});
      on('startRound',()=>{window.CRYSTAL_FEEDBACK?.reset();s.ids=sample(s.size);s.index=0;s.answers={};s.ended=false;save();repaint(true);});
      host.querySelectorAll('[data-answer]').forEach(b=>b.onclick=()=>{if(s.answers[q.id]?.checked)return;s.answers[q.id]={choice:Number(b.dataset.answer),checked:false};save();host.querySelectorAll('[data-answer]').forEach(el=>el.setAttribute('aria-pressed',String(el===b)));find('roundFeedback').hidden=true;});
      on('checkRound',()=>{if(!submit(s)){const f=find('roundFeedback');f.hidden=false;f.textContent='Choose an answer first.';return;}window.CRYSTAL_FEEDBACK?.respond(s.answers[q.id].choice===q.answer);save();repaint();find('roundFeedback').setAttribute('tabindex','-1');find('roundFeedback').focus({preventScroll:true});});
      on('drawRound',draw);
      on('prevQuestion',()=>{s.index--;save();repaint(true);});
      const end=()=>{s.ended=true;save();repaint(true);};
      const finish=()=>stats(s).attempted<s.ids.length?confirm('Finish with '+(s.ids.length-stats(s).attempted)+' unanswered questions? They will not be marked wrong. You can continue this round later.',end):end();
      on('nextQuestion',()=>{if(s.index===s.ids.length-1)finish();else{s.index++;save();repaint(true);}});
      on('endRound',finish);
      on('newRound',()=>confirm('Replace this challenge round? Export the lesson record first if you want to keep it. Your lesson answers and drawings will stay.',()=>{const size=s.size;Object.assign(s,fresh(),{size});save();repaint();find('startRound').focus();}));
      on('resumeRound',()=>{s.index=s.ids.findIndex(id=>!s.answers[id]?.checked);s.ended=false;save();repaint(true);});
      if(focus&&find('roundHeading')){find('roundHeading').focus({preventScroll:true});host.scrollIntoView({block:'start',behavior:'instant'});}
    }
    repaint();
  }
  const api={bank,sizes,levels,fresh,sample,restore,stats,question,submit,mount};
  if(typeof module==='object'&&module.exports)module.exports=api;else root.CRYSTAL_CHALLENGE=api;
})(typeof window==='object'?window:globalThis);
