/* Original teaching activities; curriculum references are teacher-facing. */
(function(root){
  'use strict';
  const phases = ['The mystery','Collect evidence','Look inside','Test your thinking','Recover the crystal','Exit challenge','Your discoveries'];
  const slides = [
    {id:'prediction',phase:0,type:'mcq',diagnostic:true,title:'The <em>vanishing</em> crystal.',lead:'A spoonful of salt. A glass of water. One very curious disappearance.',scene:'mystery',question:'We stir a little salt into water. The crystals can no longer be seen. What do you think happened?',options:['The salt has stopped existing.','The salt is still there, spread through the water.','The salt has melted into liquid salt.'],answer:1,hint:'Seeing something and knowing it exists are not always the same.',explain:'That is our idea to investigate: the salt may still be in the water even when we cannot see the crystals.',teacher:'5Cm.01, 5Cc.03. 約 5 分鐘。先聽理由，這題是預測，不計入 exit 成績。追問：What evidence would convince you? 不用要求一開始就答對。'},
    {id:'compare',phase:1,type:'compare',title:'Same water. <em>Different stories.</em>',lead:'Choose a material. Predict what stirring will do, then compare the observations.',teacher:'約 5 分鐘。鹽用少量且水足夠；沙是乾淨、不溶於水的砂粒。此為教學模型，不是測量結果。問：Does stirring always make a solid dissolve?'},
    {id:'words',phase:1,type:'reveal',title:'Give the evidence <em>a name.</em>',lead:'Use four words to explain one simple change.',scene:'solution',reveals:[['Dissolve · 溶解','A substance mixes into a solvent, spreading through it to form a solution. It has not vanished.'],['Solute · 溶質','The substance that dissolves. In our investigation, this is salt.'],['Solvent · 溶劑','The liquid that dissolves the solute. Here, it is water.'],['Solution · 溶液','The mixture we get when a solute dissolves in a solvent. Here, it is saltwater.']],teacher:'約 4 分鐘。一次揭示一個詞；先讓學生指著圖說 salt / water / saltwater，再對應科學詞彙。不要求背長定義。'},
    {id:'name-it',phase:1,type:'mcq',title:'A new drink. <em>The same idea.</em>',lead:'A little sugar dissolves completely in a cup of water.',scene:'sugar',question:'Which description identifies the solvent?',options:['The sugar, because it is the sweet part.','The whole sugar solution.','The water, because the sugar dissolves in it.'],answer:2,hint:'Find the liquid doing the dissolving.',explain:'Water is the solvent. Sugar is the solute. Together they form a sugar solution.',teacher:'約 2 分鐘。口頭延伸：Name the solute and the solution. 提醒：不要品嚐實驗材料。'},
    {id:'draw-before',phase:2,type:'written',title:'Draw what your eyes <em>cannot see.</em>',lead:'Imagine zooming into the saltwater. Make your first model before watching the animation.',scene:'zoom',prompt:'Draw the water and the salt. Add a key so someone else can read your model.',frame:'My model shows…',rubric:['Shows both water and salt.','Shows salt spread among the water particles.','Includes a key or labels.'],sample:'A labelled drawing with water particles and salt particles distributed throughout the liquid; no missing salt.',teacher:'約 4 分鐘。先收原始想法，不展示答案。允許方塊、圓點等符號。強調粒子並非真的有這些顏色，圖不是實物比例。稍後回來修圖。'},
    {id:'video',phase:2,type:'video',title:'Watch closely. <em>What changes?</em>',lead:'Follow the particles from the crystal into the water. Then explain what you noticed.',teacher:'約 4 分鐘。兩段分別為 00:44–01:00 與 01:00–01:20；已抽查畫面。原片含離子及電荷圖示，本課只追蹤「鹽的粒子分散到水中」，不考 ions、charges、polarity。影片是動畫模型，不是顯微鏡錄像。無旁白／字幕可用，請口頭引導。若播放受限，用下一頁內建模型。'},
    {id:'particles',phase:2,type:'particles',title:'Still here. <em>Just spread out.</em>',lead:'Move through the model. Track the orange symbols: do any disappear?',teacher:'約 4 分鐘。5Cm.01。此模型只呈現分散概念，不呈現水合或離子種類。鹽由離子構成；不稱作 salt molecules。溶解前後保留所有鹽符號；實際粒子一直在運動。'},
    {id:'melt',phase:3,type:'mcq',title:'Dissolving or <em>melting?</em>',lead:'An ice cube becomes liquid water in a warm room. Salt mixes into water in another cup.',scene:'melt',question:'Which comparison is correct?',options:['Both are melting because the solids disappear.','Ice melts; salt dissolves in the water.','Ice dissolves in air; salt melts in water.'],answer:1,hint:'Melting is a change from solid to liquid. Dissolving involves mixing with a solvent.',explain:'Ice changes state from solid water to liquid water. Salt dissolves by mixing through the water; it has not become liquid salt.',teacher:'約 3 分鐘。最重要的迷思檢查。請他完整說出 Salt dissolves in water; ice melts into water. 不引入熔點計算。'},
    {id:'clear',phase:3,type:'mcq',title:'Clear does not mean <em>pure.</em>',lead:'Two glasses look equally clear. One contains pure water; the other contains dissolved salt.',scene:'two-clear',question:'Can you identify pure water just by looking?',options:['No. Dissolved substances may be invisible to our eyes.','Yes. Clear liquids never contain other substances.','Yes. Saltwater must look cloudy.'],answer:0,hint:'Our saltwater became clear, but where did the salt go?',explain:'Appearance alone is not enough. A clear liquid can still contain dissolved substances. Do not taste unknown liquids to test them.',teacher:'約 2 分鐘。5ESp.02 的輕量銜接。透明≠純淨≠可飲用；不延伸整個水污染單元。'},
    {id:'fair-test',phase:3,type:'mcq',optional:true,title:'Make it <em>a fair test.</em>',lead:'You want to compare how quickly the same amount of salt dissolves in stirred and unstirred water.',scene:'test',question:'Which plan changes only the factor being investigated?',options:['Stir warm water; leave cold water unstirred.','Use more salt in the stirred cup.','Use identical cups, equal water volumes and temperatures, and equal salt amounts; stir only one.'],answer:2,hint:'If two things change, which one caused the difference?',explain:'Change stirring only. Keep the salt, water volume, temperature and cups the same. Measure the time until no crystals are visible.',teacher:'可選 3 分鐘，時間不足可跳過。5TWSp.04。改變：是否攪拌；測量：完全溶解所需時間；控制：水量、水溫、鹽量及顆粒大小、容器。這是試驗設計，不保證用更快溶解代表溶解更多。'},
    {id:'filter',phase:4,type:'filter',title:'Will a filter <em>catch it?</em>',lead:'Compare what happens when the two mixtures pass through ordinary filter paper.',teacher:'約 3 分鐘。只談 ordinary filter paper，不說所有過濾方法都無法除鹽；逆滲透不是本課範圍。先預測，按 Run filter，再看圖。沙留在紙上；已溶解的鹽跟水一起通過。'},
    {id:'boss',phase:4,type:'written',title:'Your mission: <em>bring it back.</em>',lead:'You have a salt solution, an empty shallow dish, ordinary filter paper and a warm sunny place.',scene:'recovery',prompt:'Plan how to recover the salt. Explain what leaves, what remains, and why filtering alone will not work.',frame:'First, I would… The water… The salt… Filtering alone…',rubric:['Proposes leaving the solution in a shallow dish so water can evaporate.','States that water becomes water vapour and salt remains.','Explains that dissolved salt passes through ordinary filter paper with the water.'],sample:'I would pour the solution into a shallow dish and leave it in a warm place. The water evaporates into water vapour and the salt remains. Ordinary filter paper will not trap the dissolved salt.',teacher:'約 5 分鐘。學生先寫／畫，再由老師按 Ctrl+Alt+T 評核，沒有關鍵字自動判分。只回收鹽；要收回水需凝結，留到下堂。實作可用室溫／溫暖處等待，不需要讓孩子操作加熱器。'},
    {id:'evaporation',phase:4,type:'evaporation',title:'The crystal <em>returns.</em>',lead:'Reveal the sequence. Explain the journey of the water and the salt.',teacher:'約 3 分鐘。5Cc.01、5Cc.02。太陽能使蒸發更快，但蒸發也可在室溫發生，不必沸騰。示意圖是時間壓縮，不代表數秒就蒸乾。形成晶體需足夠蒸發；不說第一滴水離開就析出鹽。'},
    {id:'exit-one',phase:5,type:'mcq',exit:true,title:'Exit challenge <em>01 / 03.</em>',lead:'Try this independently. Explain your choice before checking.',scene:'solution',question:'Why can we no longer see the salt after a little of it dissolves completely?',options:['It has turned into water.','It has escaped into the air.','Its particles are spread through the water and cannot be seen individually.'],answer:2,hint:'Use your particle model.',explain:'The salt is still present, with particles spread through the water. Dissolving does not mean the salt stops existing.',teacher:'Exit 第一題：溶解的粒子模型。系統保留第一次作答結果，重試不覆蓋第一次紀錄。'},
    {id:'exit-two',phase:5,type:'mcq',exit:true,title:'Exit challenge <em>02 / 03.</em>',lead:'A student writes: “The salt melted when I stirred it into water.”',scene:'melt',question:'Which correction should you make?',options:['Change “melted” to “dissolved”.','Change “salt” to “sand”.','No correction is needed.'],answer:0,hint:'Did the salt become liquid salt, or mix with a solvent?',explain:'The salt dissolved in water. Melting would be a change from solid salt to liquid salt.',teacher:'Exit 第二題：區分溶解與熔化。'},
    {id:'exit-three',phase:5,type:'mcq',exit:true,title:'Exit challenge <em>03 / 03.</em>',lead:'All the water in a shallow dish of salt solution slowly evaporates.',scene:'recovery',question:'What would you expect to find in the dish?',options:['Nothing: both the water and salt evaporate together.','Solid salt left behind.','Pure water left behind.'],answer:1,hint:'Which substance changed from liquid to gas?',explain:'Water leaves as water vapour. The dissolved salt is left behind as solid salt. This shows that dissolving can be reversed.',teacher:'Exit 第三題：可逆性與物質追蹤。如果三題皆正確但說不出理由，下次先用新情境查理解，不能只看分數。'},
    {id:'reflection',phase:6,type:'summary',title:'A disappearance. <em>A discovery.</em>',lead:'Good scientists revise their ideas when the evidence changes.',teacher:'約 4 分鐘。請他完成 I used to think… Now I think… because…；再問 If we want the water back too, what could we do? 下堂銜接凝結。建議 3/3 獨立答對且能解釋再前進；2/3 先用錯題作暖身；0–1/3 重做模型與回收任務。'}
  ];
  const clips = [
    {id:'separate',videoId:'xdedxfhcpWo',start:44,end:60,title:'Leaving the crystal',focus:'Follow a particle from the edge of the crystal. Where does it go?',fallback:'The salt particles separate from the crystal and become surrounded by water particles.'},
    {id:'disperse',videoId:'xdedxfhcpWo',start:60,end:80,title:'Spreading through water',focus:'Are the salt particles still visible in this model? What surrounds them?',fallback:'The salt particles are still there, distributed among the water particles.'}
  ];
  function grade(slide,choice){return Number.isInteger(choice)&&choice>=0&&choice<slide.options.length?choice===slide.answer:null;}
  function watchURL(clip){return 'https://www.youtube.com/watch?v='+clip.videoId+'&t='+clip.start+'s';}
  function embedURL(clip,origin){const p=new URLSearchParams({start:clip.start,end:clip.end,autoplay:'1',playsinline:'1',rel:'0',enablejsapi:'1'});if(/^https?:\/\//.test(origin||''))p.set('origin',origin);return 'https://www.youtube-nocookie.com/embed/'+clip.videoId+'?'+p;}
  const data={phases,slides,clips,grade,watchURL,embedURL};
  if(typeof module==='object'&&module.exports) module.exports=data; else root.CRYSTAL_LESSON=data;
})(typeof window==='object'?window:globalThis);
