-- Phase 1 of the protected module boundary.
--
-- This migration is deliberately shadow-compatible: the live portal continues
-- to use user_profiles.unlocked_modules while the new entitlement model and
-- can_launch_module() RPC are verified. No existing module route is removed.

alter table public.modules
  add column if not exists access_mode text;

update public.modules
set access_mode = 'protected'
where access_mode is null;

alter table public.modules
  alter column access_mode set default 'protected',
  alter column access_mode set not null;

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conrelid = 'public.modules'::regclass
      and conname = 'modules_access_mode_check'
  ) then
    alter table public.modules
      add constraint modules_access_mode_check
      check (access_mode in ('public', 'demo', 'protected'));
  end if;
end
$$;

-- Reconcile module cards that are already published but were never added to
-- the production registry. Existing rows are left unchanged.
insert into public.modules (id, title, syllabus, subject, bundle, grade_level, is_active)
values
  ('igcse-en-ceo-masterclass', 'CEO Masterclass (Time Heist)', 'igcse', 'english', 'igcse_english', 'IGCSE', true),
  ('igcse-y4-sci-command-centre', 'Science Command Centre 4.0', 'igcse', 'science', 'igcse_y4_science', 'Year4', true),
  ('igcse-y4-sci-operation-seven', 'Science Quest V5.4 - Operation Seven', 'igcse', 'science', 'igcse_y4_science', 'Year4', true),
  ('igcse-y8-sci-ch5', 'Chapter 5: Materials and Cycles on Earth', 'igcse', 'science', 'igcse_y8_science', 'Year8', true),
  ('igcse-y8-sci-ch6', 'Chapter 6: Light and Space', 'igcse', 'science', 'igcse_y8_science', 'Year8', true),
  ('igcse-y8-sci-ch7', 'Chapter 7: Diet and Growth', 'igcse', 'science', 'igcse_y8_science', 'Year8', true),
  ('igcse-y8-sci-ch7-mcq', 'Chapter 7: Diet and Growth (MCQ)', 'igcse', 'science', 'igcse_y8_science', 'Year8', true),
  ('kssr-p3-en-revision1', 'Revision 1 (Unit 1 and 2)', 'kssr', 'english', 'kssr_p3_english', 'Primary3', true),
  ('kssr-p3-en-revision2', 'Revision 2 (Unit 3 and 4)', 'kssr', 'english', 'kssr_p3_english', 'Primary3', true),
  ('kssr-p3-en-unit4', 'Unit 4: The Four Seasons', 'kssr', 'english', 'kssr_p3_english', 'Primary3', true),
  ('kssr-p3-en-unit5', 'Unit 5: My House Adventure', 'kssr', 'english', 'kssr_p3_english', 'Primary3', true),
  ('kssr-p6-en-revision1', 'Revision 1 (Unit 1 and 2)', 'kssr', 'english', 'kssr_p6_english', 'Primary6', true),
  ('kssr-p6-en-revision2', 'Revision 2 (Unit 1 and 2 Grammar)', 'kssr', 'english', 'kssr_p6_english', 'Primary6', true),
  ('kssr-p6-en-unit4', 'Unit 4: Interactive Worksheet', 'kssr', 'english', 'kssr_p6_english', 'Primary6', true),
  ('kssr-p6-en-unit5', 'Unit 5: Interactive English', 'kssr', 'english', 'kssr_p6_english', 'Primary6', true),
  ('kssr-p6-en-unit6', 'Unit 6: Interactive English Adventure', 'kssr', 'english', 'kssr_p6_english', 'Primary6', true),
  ('spm-bm-tatabahasa-master', 'SPM Tatabahasa Master', 'spm', 'bm', 'spm_form5', 'Form5', true),
  ('spm-chem-ch5-consumer-industrial', 'Chapter 5: Consumer and Industrial Chemistry', 'spm', 'chemistry', 'spm_form5', 'Form5', true),
  ('spm-sci-f3-bab5-termokimia', 'Bab 5: Termokimia (Thermochemistry)', 'spm', 'science', 'spm_form3', 'Form3', true),
  ('spm-sci-f3-bab6-elektrik', 'Bab 6: Elektrik dan Kemagnetan', 'spm', 'science', 'spm_form3', 'Form3', true),
  ('spm-sci-f3-bab7-tenaga', 'Bab 7: Tenaga dan Kuasa', 'spm', 'science', 'spm_form3', 'Form3', true),
  ('spm-sk-f4-bab1', 'Tingkatan 4 Bab 1: Pengaturcaraan', 'spm', 'sains komputer', 'spm_form4', 'Form4', true),
  ('spm-sk-f4-bab2', 'Tingkatan 4 Bab 2: Pangkalan Data', 'spm', 'sains komputer', 'spm_form4', 'Form4', true),
  ('spm-sk-f4-bab3', 'Tingkatan 4 Bab 3: Interaksi Manusia dan Komputer', 'spm', 'sains komputer', 'spm_form4', 'Form4', true),
  ('spm-sk-f5-bab1', 'Tingkatan 5 Bab 1: Pengkomputeran', 'spm', 'sains komputer', 'spm_form5', 'Form5', true),
  ('spm-sk-f5-bab2', 'Tingkatan 5 Bab 2: Pangkalan Data Lanjutan', 'spm', 'sains komputer', 'spm_form5', 'Form5', true),
  ('spm-sk-f5-bab3', 'Tingkatan 5 Bab 3: Pengaturcaraan Berasaskan Web', 'spm', 'sains komputer', 'spm_form5', 'Form5', true)
on conflict (id) do nothing;

-- Preserve the five legacy "first module is free" choices explicitly. Future
-- demo changes must update access_mode instead of relying on HTML card order.
update public.modules
set access_mode = 'demo'
where id in (
  'spm-en-social-media',
  'uec-en-reading',
  'igcse-en-ceo-masterclass',
  'sg-y4-math-whole-number',
  'kssr-p3-en-unit1'
);

comment on column public.modules.access_mode is
  'Explicit launch policy: public, demo, or protected. Never infer this from HTML order.';

create table if not exists public.module_entitlements (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  grant_type text not null check (grant_type in ('module', 'bundle', 'syllabus')),
  target_id text not null check (length(btrim(target_id)) > 0),
  access_level text not null default 'student' check (access_level in ('student', 'teacher')),
  source text not null check (source in ('legacy', 'pin', 'admin', 'teacher_assignment')),
  created_by uuid references auth.users(id) on delete set null,
  starts_at timestamptz not null default now(),
  expires_at timestamptz,
  revoked_at timestamptz,
  created_at timestamptz not null default now(),
  check (expires_at is null or expires_at > starts_at)
);

comment on table public.module_entitlements is
  'Auditable module, bundle, and syllabus grants. Client accounts cannot write this table directly.';

create unique index if not exists module_entitlements_one_active_grant_idx
  on public.module_entitlements (user_id, grant_type, target_id, access_level)
  where revoked_at is null;

create index if not exists module_entitlements_user_active_idx
  on public.module_entitlements (user_id, starts_at, expires_at)
  where revoked_at is null;

create index if not exists module_entitlements_target_idx
  on public.module_entitlements (grant_type, target_id)
  where revoked_at is null;

alter table public.module_entitlements enable row level security;

drop policy if exists "Users can read own module entitlements" on public.module_entitlements;
create policy "Users can read own module entitlements"
on public.module_entitlements
for select
to authenticated
using (
  (select auth.uid()) is not null
  and user_id = (select auth.uid())
);

drop policy if exists "Admins can read module entitlements" on public.module_entitlements;
create policy "Admins can read module entitlements"
on public.module_entitlements
for select
to authenticated
using (
  exists (
    select 1
    from public.user_profiles
    where user_profiles.id = (select auth.uid())
      and user_profiles.tier = 'admin'
  )
);

-- New Supabase Data API defaults require explicit grants. Entitlement writes
-- remain server-only; authenticated clients can inspect only rows allowed by RLS.
revoke all on public.module_entitlements from anon, authenticated;
grant select on public.module_entitlements to authenticated;
grant all on public.module_entitlements to service_role;
grant usage, select on sequence public.module_entitlements_id_seq to service_role;

grant select on public.modules to anon, authenticated;

-- Copy every recognised legacy unlock into the auditable grant table. The old
-- array remains untouched and is read as a fallback during the transition.
with legacy_entries as (
  select
    profiles.id as user_id,
    legacy.value
  from public.user_profiles as profiles
  cross join lateral unnest(coalesce(profiles.unlocked_modules, '{}'::text[])) as legacy(value)
), classified as (
  select
    legacy_entries.user_id,
    case
      when legacy_entries.value = 'Social_Media_Masterclass' then 'module'
      when exists (select 1 from public.modules where modules.id = legacy_entries.value) then 'module'
      when exists (select 1 from public.modules where modules.bundle = legacy_entries.value) then 'bundle'
      when exists (select 1 from public.modules where modules.syllabus = legacy_entries.value) then 'syllabus'
      else null
    end as grant_type,
    case
      when legacy_entries.value = 'Social_Media_Masterclass' then 'spm-en-social-media'
      else legacy_entries.value
    end as target_id
  from legacy_entries
)
insert into public.module_entitlements (
  user_id,
  grant_type,
  target_id,
  access_level,
  source
)
select
  classified.user_id,
  classified.grant_type,
  classified.target_id,
  'student',
  'legacy'
from classified
where classified.grant_type is not null
  and not exists (
    select 1
    from public.module_entitlements as existing
    where existing.user_id = classified.user_id
      and existing.grant_type = classified.grant_type
      and existing.target_id = classified.target_id
      and existing.access_level = 'student'
      and existing.revoked_at is null
  );

create or replace function public.can_launch_module(p_module_id text)
returns jsonb
language plpgsql
stable
security invoker
set search_path = ''
as $$
declare
  requested_module public.modules%rowtype;
  current_user_id uuid := (select auth.uid());
  current_tier text;
  current_legacy_unlocks text[] := '{}'::text[];
  matched_grant record;
  legacy_type text;
  legacy_target text;
begin
  if p_module_id is null or length(btrim(p_module_id)) = 0 then
    return jsonb_build_object(
      'allowed', false,
      'reason', 'invalid_module_id',
      'effective_role', 'guest',
      'module_id', p_module_id,
      'access_mode', null,
      'matched_grant_type', null,
      'matched_grant_target', null
    );
  end if;

  select modules.*
  into requested_module
  from public.modules
  where modules.id = p_module_id
    and coalesce(modules.is_active, true)
  limit 1;

  if not found then
    return jsonb_build_object(
      'allowed', false,
      'reason', 'module_not_found',
      'effective_role', 'guest',
      'module_id', p_module_id,
      'access_mode', null,
      'matched_grant_type', null,
      'matched_grant_target', null
    );
  end if;

  if requested_module.access_mode in ('public', 'demo') then
    return jsonb_build_object(
      'allowed', true,
      'reason', requested_module.access_mode,
      'effective_role', 'public',
      'module_id', requested_module.id,
      'access_mode', requested_module.access_mode,
      'matched_grant_type', null,
      'matched_grant_target', null
    );
  end if;

  if current_user_id is null then
    return jsonb_build_object(
      'allowed', false,
      'reason', 'authentication_required',
      'effective_role', 'guest',
      'module_id', requested_module.id,
      'access_mode', requested_module.access_mode,
      'matched_grant_type', null,
      'matched_grant_target', null
    );
  end if;

  if coalesce(((select auth.jwt()) ->> 'is_anonymous')::boolean, false) then
    return jsonb_build_object(
      'allowed', false,
      'reason', 'anonymous_account_not_allowed',
      'effective_role', 'guest',
      'module_id', requested_module.id,
      'access_mode', requested_module.access_mode,
      'matched_grant_type', null,
      'matched_grant_target', null
    );
  end if;

  select profiles.tier, coalesce(profiles.unlocked_modules, '{}'::text[])
  into current_tier, current_legacy_unlocks
  from public.user_profiles as profiles
  where profiles.id = current_user_id
  limit 1;

  if not found then
    return jsonb_build_object(
      'allowed', false,
      'reason', 'profile_required',
      'effective_role', 'guest',
      'module_id', requested_module.id,
      'access_mode', requested_module.access_mode,
      'matched_grant_type', null,
      'matched_grant_target', null
    );
  end if;

  if current_tier = 'admin' then
    return jsonb_build_object(
      'allowed', true,
      'reason', 'admin',
      'effective_role', 'admin',
      'module_id', requested_module.id,
      'access_mode', requested_module.access_mode,
      'matched_grant_type', 'admin',
      'matched_grant_target', '*'
    );
  end if;

  select entitlements.grant_type, entitlements.target_id, entitlements.access_level
  into matched_grant
  from public.module_entitlements as entitlements
  where entitlements.user_id = current_user_id
    and entitlements.revoked_at is null
    and entitlements.starts_at <= now()
    and (entitlements.expires_at is null or entitlements.expires_at > now())
    and (
      (entitlements.grant_type = 'module' and entitlements.target_id = requested_module.id)
      or (entitlements.grant_type = 'bundle' and entitlements.target_id = requested_module.bundle)
      or (entitlements.grant_type = 'syllabus' and entitlements.target_id = requested_module.syllabus)
    )
  order by
    case entitlements.access_level when 'teacher' then 0 else 1 end,
    case entitlements.grant_type when 'module' then 0 when 'bundle' then 1 else 2 end
  limit 1;

  if found then
    return jsonb_build_object(
      'allowed', true,
      'reason', 'entitlement',
      'effective_role', matched_grant.access_level,
      'module_id', requested_module.id,
      'access_mode', requested_module.access_mode,
      'matched_grant_type', matched_grant.grant_type,
      'matched_grant_target', matched_grant.target_id
    );
  end if;

  -- Transitional compatibility for PINs created before module_entitlements.
  if '*' = any(current_legacy_unlocks) then
    legacy_type := 'all';
    legacy_target := '*';
  elsif requested_module.id = any(current_legacy_unlocks) then
    legacy_type := 'module';
    legacy_target := requested_module.id;
  elsif requested_module.bundle = any(current_legacy_unlocks) then
    legacy_type := 'bundle';
    legacy_target := requested_module.bundle;
  elsif requested_module.syllabus = any(current_legacy_unlocks) then
    legacy_type := 'syllabus';
    legacy_target := requested_module.syllabus;
  elsif requested_module.id = 'spm-en-social-media'
    and 'Social_Media_Masterclass' = any(current_legacy_unlocks) then
    legacy_type := 'module';
    legacy_target := 'Social_Media_Masterclass';
  end if;

  if legacy_type is not null then
    return jsonb_build_object(
      'allowed', true,
      'reason', 'legacy_entitlement',
      'effective_role', 'student',
      'module_id', requested_module.id,
      'access_mode', requested_module.access_mode,
      'matched_grant_type', legacy_type,
      'matched_grant_target', legacy_target
    );
  end if;

  return jsonb_build_object(
    'allowed', false,
    'reason', 'not_entitled',
    'effective_role', 'student',
    'module_id', requested_module.id,
    'access_mode', requested_module.access_mode,
    'matched_grant_type', null,
    'matched_grant_target', null
  );
end;
$$;

comment on function public.can_launch_module(text) is
  'Canonical shadow-compatible launch decision for public, demo, admin, entitlement, and legacy access.';

revoke all on function public.can_launch_module(text) from public;
grant execute on function public.can_launch_module(text) to anon, authenticated;
